In [1]:
import pandas as pd 
import numpy as np 
import tensorflow as tf
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

In [2]:
data=pd.read_csv("Churn_Modelling.csv")

In [3]:
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [4]:
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [6]:
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [9]:
onehot_encoder_geo=OneHotEncoder()
geo_encoded=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

In [10]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [11]:
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)

In [12]:
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [16]:
X=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [21]:
scalar=StandardScaler()
X_train=scalar.fit_transform(X_train)
X_test=scalar.fit_transform(X_test)

In [22]:
##ANN regression problem statement training
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [25]:
#build the model
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1) #Output layer for regression
]
)

d:\ANN Classification\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [26]:
##compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])
model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [29]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Corrected timestamp format (using %S for seconds)
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

# Initialize Callbacks
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

# Since you imported EarlyStopping, you likely want to use it too:
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

# Combine them into a list for model.fit()
callbacks = [tensorboard_callback, early_stopping_callback]

In [30]:
model.fit(
    X_train, y_train, 
    epochs=100, 
    validation_data=(X_test, y_test), 
    callbacks=callbacks
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 100369.9297 - mae: 100369.9297 - val_loss: 98476.0156 - val_mae: 98476.0156
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99424.9609 - mae: 99424.9609 - val_loss: 96542.0156 - val_mae: 96542.0156
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 96068.9297 - mae: 96068.9297 - val_loss: 91638.5391 - val_mae: 91638.5391
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 89562.3359 - mae: 89562.3359 - val_loss: 83667.3594 - val_mae: 83667.3594
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 80356.5938 - mae: 80356.5938 - val_loss: 73814.3984 - val_mae: 73814.3984
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 70265.0938 - mae: 70265.0938 - val_loss: 64497.2734 - val_mae: 64497.2734
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 61458.5234 - mae: 61458.5234 - val_loss: 57430.6797 - val_mae: 57430.6797
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 55524.9062 - mae: 55524.9062 - val_loss: 53293.0000 - val_mae: 53293.0000
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 52352.3242 - mae: 52352.3242 - val_loss: 51434.0195 - val_mae: 51434.0195
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50972.6367 - mae: 50972.6367 - val_loss: 50848.1836 - val_mae: 50848.1836
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50448.8398 - mae: 50448.8398 - val_loss: 50668.0312 - val_mae: 50668.0312
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50221.3086 - mae: 50221.3086 - val_loss: 50599.3789 - val_mae: 50599.3789
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50112.0742 - mae: 50112.0742 - val_loss: 50563.0117 - val_mae: 50563.0117
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50041.5938 - mae: 50041.5938 - val_loss: 50533.6641 - val_mae: 50533.6641
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49989.6641 - mae: 49989.6641 - val_loss: 50503.3672 - val_mae: 50503.3672
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49955.1367 - mae: 49955.1367 - val_loss: 50482.9805 - val_mae: 50482.9805
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49916.2148 - mae: 49916.2148 - val_loss: 50459.3750 - val_mae: 50459.3750
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49882.8789 - mae: 49882.8789 - val_loss: 50436.6523 - val_mae: 50436.6523
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49853.3047 - mae: 49853.3047 - val_loss: 50424.7969 - val_mae: 50424.7969
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49828.2812 - mae: 49828.2812 - val_loss: 50407.6094 - val_mae: 50407.6094
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49802.7852 - mae: 49802.7852 - val_loss: 50401.4453 - val_mae: 50401.4453
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49785.8164 - mae: 49785.8164 - val_loss: 50381.1172 - val_mae: 50381.1172
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49762.4961 - mae: 49762.4961 - val_loss: 50362.1953 - val_mae: 50362.1953
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49743.8438 - mae: 49743.8438 - val_loss: 50358.6406 - val_mae: 50358.6406
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49725.6602 - mae: 49725.6602 - val_loss: 50350.8477 - val_mae: 50350.8477
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49714.7109 - mae: 49714.7109 - val_loss: 50336.5469 - val_mae: 50336.5469
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49699.4141 - mae: 49699.4141 - val_loss: 50340.6758 - val_mae: 50340.6758
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49676.1094 - mae: 49676.1094 - val_loss: 50317.8555 - val_mae: 50317.8555
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49665.4258 - mae: 49665.4258 - val_loss: 50302.5117 - val_mae: 50302.5117
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49653.2109 - mae: 49653.2109 - val_loss: 50308.6914 - val_mae: 50308.6914
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49637.4883 - mae: 49637.4883 - val_loss: 50297.9609 - val_mae: 50297.9609
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49623.8672 - mae: 49623.8672 - val_loss: 50302.8164 - val_mae: 50302.8164
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49613.6484 - mae: 49613.6484 - val_loss: 50303.1758 - val_mae: 50303.1758
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49601.5312 - mae: 49601.5312 - val_loss: 50289.0195 - val_mae: 50289.0195
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49594.6523 - mae: 49594.6523 - val_loss: 50297.2539 - val_mae: 50297.2539
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49580.7578 - mae: 49580.7578 - val_loss: 50288.2656 - val_mae: 50288.2656
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49571.8711 - mae: 49571.8711 - val_loss: 50295.5273 - val_mae: 50295.5273
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49560.6484 - mae: 49560.6484 - val_loss: 50288.0000 - val_mae: 50288.0000
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49547.6016 - mae: 49547.6016 - val_loss: 50284.5078 - val_mae: 50284.5078
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49539.2734 - mae: 49539.2734 - val_loss: 50278.9258 - val_mae: 50278.9258
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49533.3320 - mae: 49533.3320 - val_loss: 50281.8594 - val_mae: 50281.8594
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49523.1406 - mae: 49523.1406 - val_loss: 50280.3438 - val_mae: 50280.3438
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49513.9336 - mae: 49513.9336 - val_loss: 50280.3867 - val_mae: 50280.3867
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49510.4766 - mae: 49510.4766 - val_loss: 50288.0703 - val_mae: 50288.0703
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49497.5664 - mae: 49497.5664 - val_loss: 50276.4414 - val_mae: 50276.4414
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49489.2617 - mae: 49489.2617 - val_loss: 50274.7422 - val_mae: 50274.7422
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49480.4570 - mae: 49480.4570 - val_loss: 50277.1445 - val_mae: 50277.1445
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49472.4766 - mae: 49472.4766 - val_loss: 50291.1523 - val_mae: 50291.1523
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49467.0273 - mae: 49467.0273 - val_loss: 50276.9492 - val_mae: 50276.9492
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49460.5391 - mae: 49460.5391 - val_loss: 50271.2305 - val_mae: 50271.2305
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49456.6055 - mae: 49456.6055 - val_loss: 50285.5703 - val_mae: 50285.5703
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49450.1836 - mae: 49450.1836 - val_loss: 50277.3242 - val_mae: 50277.3242
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49447.6250 - mae: 49447.6250 - val_loss: 50283.5000 - val_mae: 50283.5000
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49437.6719 - mae: 49437.6719 - val_loss: 50283.6094 - val_mae: 50283.6094
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49435.9297 - mae: 49435.9297 - val_loss: 50283.7422 - val_mae: 50283.7422
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49429.0312 - mae: 49429.0312 - val_loss: 50277.6133 - val_mae: 50277.6133
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49421.4648 - mae: 49421.4648 - val_loss: 50279.4570 - val_mae: 50279.4570
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49415.3750 - mae: 49415.3750 - val_loss: 50273.1367 - val_mae: 50273.1367
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49413.8789 - mae: 49413.8789 - val_loss: 50281.0078 - val_mae: 50281.0078
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49405.6562 - mae: 49405.6562 - val_loss: 50279.0039 - val_mae: 50279.0039

In [31]:
%load_ext tensorboard

In [34]:
%tensorboard --logdir regressionlogs/fit

In [35]:
##Evaluate the model
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'test MAE: {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50271.2305 - mae: 50271.2305
test MAE: 50271.23046875

In [36]:
model.save("regression_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.